
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,filedialog,font, Frame, Label,messagebox, Scale, HORIZONTAL,BooleanVar, Checkbutton
from tkinter import ttk
import cv2
import numpy as np
from PIL import Image, ImageTk, ImageDraw
import copy
from ImageProcessing import *
DARK = "#092934"
LIGHT = "#E4EDF5"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ThinkPad\Documents\AA ACADEMIC 2024\Thesis\GUI\assets\frame0")



 ######  ########  ########    ###    ######## ########     ######   ######  ########  ######## ######## ##    ##  ######  
##    ## ##     ## ##         ## ##      ##    ##          ##    ## ##    ## ##     ## ##       ##       ###   ## ##    ## 
##       ##     ## ##        ##   ##     ##    ##          ##       ##       ##     ## ##       ##       ####  ## ##       
##       ########  ######   ##     ##    ##    ######       ######  ##       ########  ######   ######   ## ## ##  ######  
##       ##   ##   ##       #########    ##    ##                ## ##       ##   ##   ##       ##       ##  ####       ## 
##    ## ##    ##  ##       ##     ##    ##    ##          ##    ## ##    ## ##    ##  ##       ##       ##   ### ##    ## 
 ######  ##     ## ######## ##     ##    ##    ########     ######   ######  ##     ## ######## ######## ##    ##  ######  

def display_results(window):
    # Clear the window
    for widget in window.winfo_children():
        widget.destroy()

    # Create a new canvas for results
    canvas = Canvas(
        window,
        bg="#E4EDF5",
        height=1024,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)

    # Add a title
    canvas.create_text(
        720,
        50,
        text="Processing Results",
        fill="#092934",
        font=("Microsoft New Tai Lue", 24, "bold")
    )


    finish_button = Button(
        window,
        text="Finish",
        command=window.quit,
        font=("Microsoft New Tai Lue", 14),
        bg="#092934",
        fg="#E4EDF5",
        padx=20,
        pady=10
    )
    finish_button.place(relx=0.5, rely=0.9, anchor="center")
def display_final_image(window):
    # Clear the window
    for widget in window.winfo_children():
        widget.destroy()

    # Create a new canvas
    canvas = Canvas(
        window,
        bg="#E4EDF5",
        height=1024,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)

    image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
    window.edit_images.append(image_image_1)
    image_1 = canvas.create_image(
        719.0,
        57.0,
        image=image_image_1
    )

    next_button = Button(
        window,
        text= update_next_button(window),
        command=lambda: next_image(window),
        font=("Microsoft New Tai Lue", 14),
        bg="#092934",
        fg="#E4EDF5",
        padx=20,
        pady=10
    )
    next_button.place(x=1192.0, y=935.0, width=207.0, height=61.0)
    
    # Create a frame to center the image
    frame = Frame(window, bg="#E4EDF5")
    frame.place(relx=0.5, rely=0.5, anchor="center")

    # Convert the NumPy array to PIL Image
    gray_image = window.gray_image  # Make sure this is set earlier in the process
    result_grid, marked_image = detect_and_draw_circles(window.binarized_image, gray_image)

    # Ensure marked_image is a PIL Image
    if isinstance(marked_image, np.ndarray):
        marked_image = Image.fromarray(marked_image)

    # Convert to "RGB" mode if not already
    if marked_image.mode not in ["RGB", "RGBA"]:
        marked_image = marked_image.convert("RGB")

    # Resize the image to fit the window (adjust as needed)
    max_size = (1000, 800)  # Maximum width and height
    marked_image.thumbnail(max_size, Image.Resampling.LANCZOS)

    # Convert to PhotoImage
    photo = ImageTk.PhotoImage(marked_image)

    # Create a label to display the image
    image_label = Label(frame, image=photo, bg="#E4EDF5")
    image_label.image = photo  # Keep a reference
    image_label.pack()


    # Add a "Back to Editing" button
    back_button = Button(
        window,
        text="Back to Editing",
        command=lambda: process_image(window),
        font=("Microsoft New Tai Lue", 14),
        bg="#092934",
        fg="#E4EDF5",
        padx=20,
        pady=10
    )
    back_button.place(relx=0.5, rely=0.9, anchor="center")




    window.progress_frame = Frame(window, bg="#E4EDF5")
    window.progress_frame.place(x=1200, y=20, width=200, height=50)
    
    window.progress_bar = ttk.Progressbar(window.progress_frame, orient="horizontal", length=150, mode="determinate")
    window.progress_bar.pack(side="left", padx=(0, 10))
    
    window.progress_label = Label(window.progress_frame, text="", bg="#E4EDF5", font=("Microsoft New Tai Lue", 12))
    window.progress_label.pack(side="left")
    
    update_progress_bar(window)


def update_progress_bar(window):
    if hasattr(window, 'progress_bar') and window.progress_bar:
        progress = (window.current_image_index + 1) / len(window.image_paths) * 100
        window.progress_bar['value'] = progress
        window.progress_label.config(text=f"{window.current_image_index + 1}/{len(window.image_paths)}")

def next_image(window):
    if window.current_image_index < len(window.image_paths) - 1:
        window.current_image_index += 1
        load_current_image(window)
        create_editFrame(window)
    else:
        display_results(window)
    update_progress_bar(window)
def update_next_button(window):
    if hasattr(window, 'next_button') and window.next_button:
        if window.current_image_index == len(window.image_paths) - 1:
            return ("Results")
        else:
            return ("Next Image")
    
def create_titleFrame(window):
    canvas = Canvas(
        window,
        bg="#E4EDF5",
        height=1024,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
   
    image_image_10 = PhotoImage(file=relative_to_assets("image_10.png"))
    image_image_10 = image_image_10.subsample(2, 2)
    image_1 = canvas.create_image(720.0, 464.0, image=image_image_10)
   
    # button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    
    # button_1 = Button(
    #     window,
    #     image=button_image_1,
    #     borderwidth=0,
    #     highlightthickness=0,
    #     command=lambda: upload_image(window),
    #     relief="flat"
    # )
    button_1 = Button(
        window,
        text="Upload Assays",
        command=lambda: upload_images(window),
        font=("Microsoft New Tai Lue", 14),
        bg="#092934",
        fg="#E4EDF5",
        padx=20,
        pady=10
    )
    button_1.place(x=616.0, y=739.0, width=207.0, height=61.0)
   

    button_2 = Button(
        window,
        text="Upload MetaData",
        font=("Microsoft New Tai Lue", 14),
        bg="#092934",
        fg="#E4EDF5",
        padx=20,
        pady=10,
        command=lambda: upload_txt_file(window)
       
    )
    button_2.place(x=616.0, y=800.0, width=207.0, height=61.0)
   
    button_image_3 = PhotoImage(file=relative_to_assets("button_1.png"))
    button_3 = Button(
        window,
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: process_image(window),
        relief="flat"
    )
    button_3.place(x=616.0, y=861.0, width=207.0, height=61.0)
   
    #return canvas, image_image_10, button_image_1, button_1, button_image_2, button_2, button_image_3, button_3
    return canvas, image_image_10, button_1, button_2, button_image_3, button_3
def update_button_appearance(window, button, active_mode, active_image, inactive_image):
    if window.mode == active_mode:
        button.config(image=active_image)
    else:
        button.config(image=inactive_image)

def process_image(window):
    # Destroy all widgets in the window
    for widget in window.winfo_children():
        widget.destroy()
    
    # Create the edit frame
    create_editFrame(window)

def create_editFrame(window):

    canvas = Canvas(
        window,
        bg="#E4EDF5",
        height=1024,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    window.edit_images = []

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    window.edit_images.append(image_image_1)
    image_1 = canvas.create_image(
        719.0,
        57.0,
        image=image_image_1
    )

    window.show_original = True  # Initialize with showing the original image
    toggle_button = Button(
        window,
        text="Toggle Image",
        command=lambda: toggle_image(window),
        bg=DARK,
        fg=LIGHT,
        activebackground=DARK,
        activeforeground=LIGHT
    )
    toggle_button.place(x=100, y=935)



    smallDots_label = Label(window, text="Area to ignore:", bg=DARK, fg="white")
    smallDots_label.place(x=500, y=140)

    smallDots_slider = Scale(window, from_=0, to=10000, orient=HORIZONTAL, length=200,
                            command=lambda v: on_excludeSmallDots(window, v),
                            bg=DARK, fg="white", troughcolor="#E4EDF5")
    smallDots_slider.set(window.excludeSmallDots)  # Set default value
    smallDots_slider.place(x=500, y=130)




    contrast_label = Label(window, text="Contrast:", bg=DARK, fg="white")
    contrast_label.place(x=34, y=140)

    contrast_slider = Scale(window, from_=0, to=40, orient=HORIZONTAL, length=200,
                            command=lambda v: on_contrast_change(window, v),
                            bg=DARK, fg="white", troughcolor="#E4EDF5")
    contrast_slider.set(window.contrast_value)  # Set default value
    contrast_slider.place(x=100, y=130)

    button_image_1 = PhotoImage( #this is the next button
        file=relative_to_assets("button_1.png"))
    window.edit_images.append(button_image_1)
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: display_final_image(window),
        relief="flat"
    )
    button_1.place(
        x=1192.0,
        y=935.0,
        width=207.0,
        height=61.0
    )

    round_rectangle(canvas,
       1331.0,
        168.0,
        1422.0,
        826.0,
        fill="#0C2934",
        outline="")

    round_rectangle(canvas,
        17.0,
        168.0,
        1324.0,
        826.0,
        fill="#0C2934",
        outline="")

    if hasattr(window, 'metadata'):
        metadata_label = Label(canvas, text=window.metadata, font=("Microsoft New Tai Lue", 16 * -1, 'bold'))
    else:
        metadata_label = Label(canvas, text="No metadata available", font=("Microsoft New Tai Lue",16 * -1,'bold'))
    metadata_label.place(x=50, y=50)

    # canvas.create_text(
    #     34.0,
    #     872.0,
    #     anchor="nw",
    #     text=window.metadata,
    #     fill="#0C2934",
    #     font=("Microsoft New Tai Lue",16 * -1,'bold')
    # )

    canvas.create_text(
        1344.0,
        325.0,
        text="Add",
        fill="#E4EDF5",
        font=("Microsoft New Tai Lue", 16 * -1,'bold')
    )

    canvas.create_text(
        1338.0,
        537.0,
        text="Delete",
        fill="#E4EDF5",
        font=("Microsoft New Tai Lue", 16 * -1,'bold')
    )

    # round_rectangle(canvas,
    #     77.0,
    #     282.0,
    #     701.0,
    #     862.0,
    #     fill="#E4EDF5",
    #     outline="")

    # round_rectangle(canvas,
    #     738.0,
    #     282.0,
    #     1362.0,
    #     862.0,
    #     fill="#E4EDF5",
    #     outline="")

    image_image_2 = PhotoImage( #this is the thin pen
        file=relative_to_assets("image_2.png"))
    image_image_2 = image_image_2.subsample(8, 8) 
    window.edit_images.append(image_image_2)
    button_thin_pen = Button(
        window,
        image=image_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: set_mode(window, "thin_brush"),
        bg= DARK
   
    )
    
    button_thin_pen.place(x=1377.0, y=480.0)




    image_image_3 = PhotoImage(# this is the magic adder
        file=relative_to_assets("image_3.png"))
    image_image_3 = image_image_3.subsample(8, 8)
    window.edit_images.append(image_image_3)
    magic_adder_button = Button(
        window,
        image=image_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("adder"),
        relief="flat",
        bg = DARK
    )
    magic_adder_button.place(x=1376,y=402)


    # Big eraser
    image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))
    image_image_4 = image_image_4.subsample(8, 8) 
    window.edit_images.append(image_image_4)
    big_eraser_button = Button(
        window,
        image=image_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: set_mode(window, "large_brush"),
        relief="flat",
        bg = DARK
    )
    big_eraser_button.place(x=1377.0, y=655.0)

    image_image_5 = PhotoImage(#this is the bi gpen
        file=relative_to_assets("image_5.png"))
    image_image_5 = image_image_5.subsample(8, 8) 
    window.edit_images.append(image_image_5)
    big_pen_button = Button(
        window,
        image=image_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: set_mode(window, "large_brush"),
        relief="flat",
        bg = DARK
    )
    big_pen_button.place(x=1377, y=441)


    # Flood eraser (magic eraser)
    image_image_6 = PhotoImage(file=relative_to_assets("image_6.png"))
    image_image_6 = image_image_6.subsample(8, 8)
    window.edit_images.append(image_image_6)
    
    flood_eraser_button = Button(
        window,
        image=image_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: set_mode(window, "flood"),
        relief="flat",
        bg = DARK
    )
    flood_eraser_button.place(x=1376.0, y=616.0)

    image_image_7 = PhotoImage( #this is the redo button
        file=relative_to_assets("image_7.png"))
    image_image_7 = image_image_7.subsample(8, 8)
    window.edit_images.append(image_image_7)

    redo_button = Button(
        window,
        image=image_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("redo"),
        relief="flat",
        bg = DARK
    )
    redo_button.place(x=1380.0, y=251.0)


    image_image_8 = PhotoImage( #this is the undo button 
        file=relative_to_assets("image_8.png"))
    image_image_8 = image_image_8.subsample(8, 8)
    window.edit_images.append(image_image_8)
    undo_button = Button(
        window,
        image=image_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: undo(window),
        relief="flat",
        bg = DARK
    )
    undo_button.place(x=1371.0, y=212.0)


    # Thin eraser
    image_image_9 = PhotoImage(file=relative_to_assets("image_9.png"))
    image_image_9 = image_image_9.subsample(8, 8)
    window.edit_images.append(image_image_9)
    thin_eraser_button = Button(
        window,
        image=image_image_9,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: set_mode(window, "small_brush"),
        relief="flat",
        bg = DARK
    )
    thin_eraser_button.place(x=1376.0, y=693.0)

    window.undo_button = undo_button
    window.redo_button = redo_button
    ######Adding images:
    # Resize the image to fit the space of rectangles 3 and 4
     # Calculate dimensions
     # Calculate dimensions
    total_width = 1295 - 34
    total_height = 783 - 203
    img_width = total_width // 2  # Half of the total width for each image
    img_height = total_height

    window.left_canvas = Canvas(window, width=img_width, height=img_height, bg=DARK, highlightthickness=0)
    window.left_canvas.place(x=34, y=203)

    window.right_canvas = Canvas(window, width=img_width, height=img_height, bg=DARK, highlightthickness=0)
    window.right_canvas.place(x=690, y=203)

    # Display images
    display_images(window)

    # Bind events for editing on both canvases
    for canvas in [window.left_canvas, window.right_canvas]:
        canvas.bind("<ButtonPress-1>", lambda event: start_draw(window, event))
        canvas.bind("<B1-Motion>", lambda event: draw(window, event))
        canvas.bind("<ButtonRelease-1>", lambda event: stop_draw(window, event))

    # Connect buttons to functions
    button_thin_pen.config(command=lambda: set_mode(window, "small_brush"))
    big_pen_button.config(command=lambda: set_mode(window, "large_brush"))
    thin_eraser_button.config(command=lambda: set_mode(window, "small_eraser"))
    big_eraser_button.config(command=lambda: set_mode(window, "large_eraser"))
    flood_eraser_button.config(command=lambda: set_mode(window, "flood"))
    undo_button.config(command=lambda: undo(window))
    redo_button.config(command=lambda: redo(window))






    window.progress_frame = Frame(window, bg="#E4EDF5")
    window.progress_frame.place(x=1200, y=20, width=200, height=50)
    
    window.progress_bar = ttk.Progressbar(window.progress_frame, orient="horizontal", length=150, mode="determinate")
    window.progress_bar.pack(side="left", padx=(0, 10))
    
    window.progress_label = Label(window.progress_frame, text="", bg="#E4EDF5", font=("Microsoft New Tai Lue", 12))
    window.progress_label.pack(side="left")
    
    update_progress_bar(window)




    return canvas


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def round_rectangle(canvas,x1, y1, x2, y2, radius=35, **kwargs):
        
    points = [x1+radius, y1,
              x1+radius, y1,
              x2-radius, y1,
              x2-radius, y1,
              x2, y1,
              x2, y1+radius,
              x2, y1+radius,
              x2, y2-radius,
              x2, y2-radius,
              x2, y2,
              x2-radius, y2,
              x2-radius, y2,
              x1+radius, y2,
              x1+radius, y2,
              x1, y2,
              x1, y2-radius,
              x1, y2-radius,
              x1, y1+radius,
              x1, y1+radius,
              x1, y1]

    return canvas.create_polygon(points, **kwargs, smooth=True)

# db    db d8888b. db       .d88b.   .d8b.  d8888b. .d8888. 
# 88    88 88  `8D 88      .8P  Y8. d8' `8b 88  `8D 88'  YP 
# 88    88 88oodD' 88      88    88 88ooo88 88   88 `8bo.   
# 88    88 88~~~   88      88    88 88~~~88 88   88   `Y8b. 
# 88b  d88 88      88booo. `8b  d8' 88   88 88  .8D db   8D 
# ~Y8888P' 88      Y88888P  `Y88P'  YP   YP Y8888D' `8888Y' 


def upload_txt_file(window):
    file_path = filedialog.askopenfilename(filetypes=[("Text files", "*.txt")])
    if file_path:
        with open(file_path, 'r') as file:
            content = file.read().strip()
            parts = content.split(',')
            if len(parts) == 4:
                strains = [part.strip() for part in parts[:3]]
                atp = parts[3].strip().lower()
                strain_info = ', '.join([f'Strain {s}' for s in strains])
                atp_info = 'ATP: YES' if atp == 'yes' else 'ATP: NO'
                window.metadata = f"{strain_info}\n{atp_info}"
            else:
                messagebox.showerror("Error", "The uploaded file is not in the expected format. The format should be: 'A,B,C,YES/NO'.")

def upload_images(window):
    file_paths = filedialog.askopenfilenames(filetypes=[("Image files", "*.png *.jpg *.jpeg *.bmp *.gif")])
    if file_paths:
        window.image_paths = list(file_paths)
        window.current_image_index = 0
        load_current_image(window)

def load_current_image(window):
    window.image_path = window.image_paths[window.current_image_index]
    window.original_image = cv2.imread(window.image_path)
    
    # Apply perspective correction
    window.original_image = correct_perspective_pipeline(window.original_image)

    stretched, blurred, gray_image = stretch_and_gray(window.original_image, 90, 150)
    window.gray_image = gray_image
    binary_image, contour_img, final_binary, block_size = binarize(window.gray_image, window.original_image, excludeSmallDots=window.excludeSmallDots, contrast=window.contrast_value)
    
    window.contour_img = contour_img
    window.binarized_image = final_binary
    window.debug_image = np.stack((final_binary,) * 3, axis=-1)
    
    # Initialize history with the binarized image
    window.history = [window.binarized_image.copy()]
    window.redo_stack = []
    update_undo_redo_buttons(window)
        
##     ##  #######  ########  ########  ######  
###   ### ##     ## ##     ## ##       ##    ## 
#### #### ##     ## ##     ## ##       ##       
## ### ## ##     ## ##     ## ######    ######  
##     ## ##     ## ##     ## ##             ## s
##     ## ##     ## ##     ## ##       ##    ## 
##     ##  #######  ########  ########  ###### 


def on_contrast_change(window, value):
    window.contrast_value = float(value)
    binary_image, contour_img, final_binary, block_size = binarize(window.gray_image, window.original_image, contrast=window.contrast_value, excludeSmallDots=window.excludeSmallDots)

    # Update the binarized image and contour image
    window.binarized_image = final_binary
    window.contour_img = contour_img
    window.debug_image = np.stack((final_binary,) * 3, axis=-1)

    # Update the history
    add_to_history(window)

    # Refresh the displayed images
    display_images(window)

def on_excludeSmallDots(window,value):
    window.excludeSmallDots =float(value)
    binary_image, contour_img, final_binary, block_size = binarize(window.gray_image, window.original_image, contrast=window.contrast_value, excludeSmallDots=window.excludeSmallDots)

    # Update the binarized image
    window.binarized_image = final_binary
    
    window.debug_image = np.stack((final_binary,) * 3, axis=-1)
    
    # Update the history
    add_to_history(window)

    # Refresh the displayed images
    display_images(window)
def set_mode(window, mode):
    window.mode = mode
    if mode == "small_brush" or mode == "small_eraser":
        window.brush_size = 40
    elif mode == "large_brush" or mode == "large_eraser":
        window.brush_size = 120

def toggle_image(window):
    window.show_original = not window.show_original
    display_images(window)

def display_images(window):
    try:
        # Right image (editing image)
        img_editing = Image.fromarray(window.debug_image)
        img_editing.thumbnail((window.winfo_width()//2 - 60, window.winfo_height() - 200))
        window.photo_editing = ImageTk.PhotoImage(img_editing)
        window.right_canvas.config(width=window.photo_editing.width(), height=window.photo_editing.height())
        window.right_canvas.create_image(0, 0, anchor="nw", image=window.photo_editing)
       
        window.display_width = window.photo_editing.width()
        window.display_height = window.photo_editing.height()

        # Left image (toggleable)
        if window.show_original:
            img_left = Image.open(window.image_path)
            img_left = img_left.convert("RGB")
        else:
            img_np = np.array(window.original_image)
            img_editing_resized = cv2.resize(np.array(img_editing), (img_np.shape[1], img_np.shape[0]))
            img_gray = cv2.cvtColor(img_editing_resized, cv2.COLOR_RGB2GRAY)
            contours, _ = cv2.findContours(img_gray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            contour_img = img_np.copy()
            for cntr in contours:
                cv2.drawContours(contour_img, [cntr], 0, (0, 255, 255), 2)
            img_left = Image.fromarray(contour_img)

        img_left.thumbnail((window.winfo_width()//2 - 60, window.winfo_height() - 200))
        window.photo_left = ImageTk.PhotoImage(img_left)
        window.left_canvas.config(width=window.photo_left.width(), height=window.photo_left.height())
        window.left_canvas.create_image(0, 0, anchor="nw", image=window.photo_left)

    except Exception as e:
        print(f"Error in display_images: {e}")


def start_draw(window, event):
    window.is_drawing = True
    window.last_x = event.x
    window.last_y = event.y
    window.active_canvas = event.widget
    draw(window, event)

def draw(window, event):
    if window.is_drawing:
        x, y = event.x, event.y
        img_height, img_width = window.binarized_image.shape[:2]
        scale_x = img_width / window.display_width
        scale_y = img_height / window.display_height

        x_img = int(x * scale_x)
        y_img = int(y * scale_y)
        last_x_img = int(window.last_x * scale_x)
        last_y_img = int(window.last_y * scale_y)

        if window.mode == "flood":
            flood_erase(window, x_img, y_img)
        else:
            brush_draw(window, last_x_img, last_y_img, x_img, y_img)

        window.last_x = x
        window.last_y = y
        display_images(window)

def stop_draw(window, event):
    window.is_drawing = False
    current_state = window.binarized_image.copy()
    if len(window.history) == 0 or not np.array_equal(current_state, window.history[-1]):
        add_to_history(window)
    update_undo_redo_buttons(window)

def flood_erase(window, x, y):
    if window.binarized_image[y, x] == 255:  # If the clicked pixel is white
        cv2.floodFill(window.binarized_image, None, (x, y), 0)  # Fill with black
        window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)

def brush_draw(window, x1, y1, x2, y2):
    if window.mode in ["small_brush", "large_brush"]:
        color = 255  # White color for drawing
    else:
        color = 0  # Black color for erasing
    cv2.line(window.binarized_image, (x1, y1), (x2, y2), color, window.brush_size)
    window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
    cv2.line(window.debug_image, (x1, y1), (x2, y2), (0, 0, 255), 2)

def brush_erase(window, x1, y1, x2, y2):
    cv2.line(window.binarized_image, (x1, y1), (x2, y2), 0, window.brush_size * 2)
    window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
    cv2.line(window.debug_image, (x1, y1), (x2, y2), (0, 0, 255), 2)
def add_to_history(window):
    current_state = window.binarized_image.copy()
    if not window.history or not np.array_equal(current_state, window.history[-1]):
        window.history.append(current_state)
        window.redo_stack.clear()
        update_undo_redo_buttons(window)

def undo(window):
    if len(window.history) > 1:
        current_state = window.binarized_image.copy()
        window.redo_stack.append(current_state)
        window.binarized_image = window.history.pop().copy()
        window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
        display_images(window)
    elif len(window.history) == 1:
        # If there's only one item in history, it's the original image
        current_state = window.binarized_image.copy()
        if not np.array_equal(current_state, window.history[0]):
            window.redo_stack.append(current_state)
            window.binarized_image = window.history[0].copy()
            window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
            display_images(window)
    update_undo_redo_buttons(window)

def redo(window):
    if window.redo_stack:
        window.history.append(window.binarized_image.copy())
        window.binarized_image = window.redo_stack.pop().copy()
        window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
        display_images(window)
        update_undo_redo_buttons(window)

def update_undo_redo_buttons(window):
    if hasattr(window, 'undo_btn') and window.undo_btn is not None:
        window.undo_btn['state'] = "normal" if len(window.history) > 1 else "disabled"
    if hasattr(window, 'redo_btn') and window.redo_btn is not None:
        window.redo_btn['state'] = "normal" if window.redo_stack else "disabled"

def brush_draw(window, x1, y1, x2, y2):
    if window.mode in ["small_brush", "large_brush"]:
        color = 255  # White color for drawing
    else:
        color = 0  # Black color for erasing
    cv2.line(window.binarized_image, (x1, y1), (x2, y2), color, window.brush_size)
    window.debug_image = np.stack((window.binarized_image,) * 3, axis=-1)
    cv2.line(window.debug_image, (x1, y1), (x2, y2), (0, 0, 255), 2)

def initialize_window_attributes(window):
    window.window_width = 1440
    window.window_height = 1024
    window.history = []
    window.undo_btn = None
    window.redo_btn = None
    window.redo_stack = []
    window.mode = "small_brush"
    window.brush_size = 5
    window.is_drawing = False
    window.last_x = None
    window.last_y = None
    window.update_undo_redo_buttons = update_undo_redo_buttons
    window.display_images = display_images
    window.excludeSmallDots = 1000
    window.contrast_value = 20
    window.image_paths = []
    window.current_image_index = 0
    window.next_button = None
    window.progress_bar = None
    window.progress_label = None

window = Tk()
window.geometry("1440x1024")
window.configure(bg="#E4EDF5")
window.title("SpotPlotter")
window.iconbitmap(r'C:\Users\ThinkPad\Documents\AA ACADEMIC 2024\Thesis\GUI\ICONS\ICON.ico')
#DFAULT VALUES

initialize_window_attributes(window)
# Create the title frame
title_frame_widgets = create_titleFrame(window)

window.resizable(True, True)
window.mainloop()
